### PR TITLE
Meteor integration

### PR DESCRIPTION
**Pull request by splendido**
Hi Jack,

As you might know, the [Meteor](https://www.meteor.com/) community loves Semantic-UI. We had many different wrapper packages all doing the same thing, so I'm submitting a PR that integrates Meteor packaging directly into your repository.

All you have to do after accepting this PR is:

1. create an account at https://meteor.com/ (click SIGN IN, then Create account). After you've done that, please let me know the name of the account, and I'll add you as a maintainer of the `semantic` organization (which has been alredy reserved for you).

2. head to [Meteor Autopublish](http://autopublish.meteor.com/) sign in with your gitHub account, locate this repository and enable it for autopublish by toggling the checkbox you'll find on the right side of the repository item. You can get an idea about how Meteor Autopublish works by having a quick look at [this page](http://autopublish.meteor.com/howitworks), but basically it creates a [web hook](https://help.github.com/articles/about-webhooks/) to let us know when you push new tags.

Please note that I've already published the current version of the package on [Atmosphere](https://atmospherejs.com/semantic/ui) (Meteor's package directory). When you'll release new versions, autopublish.meteor.com will automatically take delivery for publishing the new version also for Meteor.

Thanks & best regards,
Luca & the [Meteor integrations team](https://github.com/raix/Meteor-community-discussions/issues/14)

### CODE REVIEW

**Comment by jlukic** [comment]
Thanks. I'll review on Monday when I'm back at the office

**Comment by jlukic** [comment]
### Next Steps

* My username on meteor.com is `jlukic`
* I have authorized GitHub usage for Autopublish. I'm seeing the message "Repository is not a meteor package". 
* I am assuming this will disappear once we have a `package.js` in `master`. When that happens I'll make the swap on autopublish.
* I've merged this PR into branch `meteor`. This most likely won't make `next` until it is fine tuned
* Take a look at commits tagged to this PR, let me know if this looks ok.

### Code Notes

------

```javascript
  // updates package.js
  console.info('Updating package.js (Meteor)');
  var
    assetPath = output.themes + 'default/assets/',
    fnames =
      '    \'' + output.packaged + 'semantic.css\',\n' +
      '    \'' + output.packaged + 'semantic.js\',\n'
  ;
  gulp.src(assetPath + '**', {base: assetPath})
    .pipe(concatFnames("dummy.txt", {
      newline: '',
      root: './',
      prepend: '    \'',
      append: '\','
    }))
    .pipe(tap(function(file) { fnames += file.contents; }))
    .on('end', function() {
      gulp.src(release.templates.meteor)
        .pipe(plumber())
        .pipe(flatten())
        .pipe(replace('{package-version}', version))
        .pipe(replace('{package-files}', fnames))
        .pipe(gulp.dest('./'))
      ;
    })
  ;
```
* Do meteor packages need to have all filenames from dist/ mentioned explicitly i.e. `{package-files}`? 
* This should be moved to `gulp release`. I think I will split `gulp release` into two tasks. 
** `gulp release all`` will release SUI across multiple repos (single UI component repos).
** `gulp release` will run `npm publish` and build `package.js` for Meteor

I think creating this list in `gulp` isn't necessary if `package.js` is parsed by Node/Meteor. We can use native node FS functions inside `package.js` to attach files. 

Ideally we can just use globs in `api.addFiles` if it is supported:
```javascript
Package.onUse(function(api) {
  api.addFiles([ 'dist/**/*' ], where); // psuedo code 
});
```

If not we can use the [glob package](https://github.com/isaacs/node-glob) and a simpler method for grabbing file names like
```javascript
var glob = require('glob');
glob("dist/**/*", function (error, files) {
 // files is array of files.
})
```

* There is also a variable `version` available in task scope, that has the current version from `package.json` so we can avoid `{meteor-version}`

* I've moved `meteor/test` folder into main ``test/`` for organizational reasons
* I've simplified some names and removed abbreviations
* What is the purpose of `meteor/` folder? Sorry I've probably forgotten from our previous conversations

**Comment by splendido** [comment]
All of your changes are more than fine so far!

Are you also fine with the package name `semantic:ui`?
or would you prefer a more *complete* `semanticorg:semantic-ui`?

Some answers to your points:
- yeah, on autopublish you'll be able to enable SUI repos as soon as you'll have a package.js file on the master brach
- since you already moved the test files out of the meteor folder, I guess it is no more necessary. So feel free to remove it. The only thing would be leaving the possibility to havea more detailed (stand-alone?) README file dedicated to Meteor where we could put some more details about how to initialize SUI modules (I.e.) and some best practices... But this is mostly up to you I guess...
- I'm not sure globs are supported inside the `package.js` file (I'll give them a try...) but I'm quite sure you can require the `glob` package, even if the correct form would be `var glob = Npm.require('glob');` and you'll need to use the synchronous version `glob.sync`. So something like:

```javascript
var
  glob = Npm.require('glob')
  files = glob.sync("dist/**/*")
;

Package.onUse(function(api) {
  api.addFiles(files, ['client']);
});
```

should be fine. I'll try to test it an let you know.

At this point I'd probably try something on the following lines:

```javascript
var
  glob = Npm.require('glob')
  assets = glob.sync("dist/themes/defaul/assets/**/*", options)
;

Package.onUse(function(api) {
  api.addFiles([
    'dist/semantic.css',
    'dist/semantic.js'
  ], 'client');

  api.addFiles(assets, 'client', {isAsset: true});
});
```

The only thing to update inside this file, at this point, would be the version number which might be a simple replace from a gulp task?

**Comment by splendido** [comment]
The good news is that you can use `glob` inside `package.js` file..

The bad news are:
- when the `package.js` file is *evaluated* the current path is the application's path and **not** the package's path
- it seems there's no easy/official way to get the package's path from within the package.js file (and specified paths are [intended to be relative](https://github.com/meteor/meteor/blob/68808ac288fa5acf9f0fc81c4de92c12a9a147a0/tools/package-source.js#L1152-1164) to the package's folder to be included later on)

Actually there's a bit of ongoing discussion about this:
- https://github.com/meteor/meteor/issues/1733
- http://stackoverflow.com/questions/20912858/using-npm-packages-in-meteor-package-js
- https://github.com/meteor/meteor/issues/2559

But my conclusion would be: it is better to list files as plain string arrays! ;-)

At this point, if you're not too much uncomfortable with it, I'd keep the file listing inside a grunt task.
Unless we prefer to keep a static file list inside the `pacakge.js` file and update only the version number.

**Comment by splendido** [comment]
Any news on this @jlukic?

**Comment by jlukic** [comment]
I'm currently working on a rewrite of the `gulpfile.js` that isn't complete. 

Trying to resolve several build tools issues in *one fell swoop*. Probably end of week or early next week.

**Comment by splendido** [comment]
Brilliant!
...let me know when you'll reach a stable state: there are a coupe of things to be changed in the `package.js` template file. And I might also try to put some better contents into the README for meteor (see https://github.com/Semantic-Org/Semantic-UI/issues/1618#issuecomment-72310597)

**Comment by jlukic** [comment]
I know it keeps getting delayed, but wanted to let you know I am still working on this. 
https://github.com/Semantic-Org/Semantic-UI/commits/meteor

**Comment by splendido** [comment]
...I'm silently following ;-)
Take your time,  just let me know when you get there. 

Tnx for the update, really appreciated!

**Comment by jasonxeno** [comment]
@jlukic I see you feverishly working on this and your amusing commit messages, I just wanted to express my gratitude in supporting Meteor, I look forward to using this!

**Comment by jlukic** [comment]
So I'm nearly ready to launch. A lot has changed in the build tools. You can read an overview in the src [readme](https://github.com/Semantic-Org/Semantic-UI/blob/next/src/README.md)] and the `1.9.0` [release notes](https://github.com/Semantic-Org/Semantic-UI/blob/next/RELEASE-NOTES.md)

With regard to Meteor packages. I would like to find a way to make the official package include theming. Now that less files are directly importable this may be much easier. Anyone have experience using atmosphere packages with `less`? The site theme still needs to be stored outside of your package managed folder, but this seems like a simple cut & paste job. Any thoughts here?

My concern with launching with official packages and including only static css is that it will be very difficult to swap to themed versions later.

**Comment by jlukic** [comment]
Another note, it looks like we can use `npm.depends` now in `package.js`
https://github.com/meteor/meteor/issues/2559#issuecomment-72787646

**Comment by splendido** [comment]
Hi @jlukic!

If you wish to keep the `semantic:ui` name for the less version we might use `semantic:ui-css` for the satic one, if you think it might be something worth having.

Getting back to LESS and theming, to my best knowledge the most successfull approach in this direction is [nemo64:bootstrap](https://atmospherejs.com/nemo64/bootstrap).
It allows for the user to create a file with which select which **modules** to import.

I guess working on those lines might allow for selecting different themes as well!

...but unfortunately I'm not in a position to help with this :(
Hopefully someone else will, or we might try to contact nemo64 and see whether he would be available to replicate and adapt is approach also for SUI!

Thoughts?

**Comment by jlukic** [comment]
I'm going to launch today with `semantic:ui` and `semantic:ui-css` in `package.js` in [less](https://github.com/Semantic-Org/Semantic-UI-LESS) and [css](https://github.com/Semantic-Org/Semantic-UI-CSS) repos.

I'll remove `package.js` from the main repo. 

if we ever come up with a solution down the road or contributors to help, I'll move things over.

**Comment by jlukic** [comment]
@splendido 

Just turned like 50 sliders for autopublish on all component packages and css less builds using your tool at: http://autopublish.meteor.com/

Files are grabbed with a simple walk since [native NPM packages should be supported](https://github.com/meteor/meteor/issues/2559#issuecomment-72787646)

Is there anyway someone could test from Meteor?

**Comment by splendido** [comment]
Awesome!
...I've just seen you already registered everything on autopublish.meteor.com
The automated publishing will start from the next release though since there won't be any hook trigger for past releases.
I might try to automatically send **fake** triggers if you wish...

**Comment by jlukic** [comment]
Yeah that sounds good, fake trigger away!

**Comment by splendido** [comment]
I'm going to bed now, but I can test them tomorrow...
...in case it's not too late!

**Comment by jlukic** [comment]
Tomorrow is great, thanks for all your help

**Comment by splendido** [comment]
...so should I already fake trigger everything to publish 1.9.1 versions?

Btw, there might be no advantages with the LESS versions of the packages since all `.less` files will be automatically compiled by Meteor before anyone can even try to change some variables' values...
We'll have to sort something out...

I'll let you know for the tests!
Good night!

**Comment by splendido** [comment]
...actually some repo seems to be at `1.9.0` and some other at `1.9.2`!
at least from what autopublish.meteor.com detected.

Is this correct?

**Comment by splendido** [comment]
Single component repos seem to have some problem with the list of files to be added!
see [this line](https://github.com/Semantic-Org/UI-Step/blob/master/package.js#L15) to link one...

**Comment by jlukic** [comment]
Crap. Will have to fix tomorrow

**Comment by splendido** [comment]
another missing thing for the LESS version is requiring the use of the `less` package to compile sources into css files. Differently `.less` files will be ignored...

[This is the line](https://github.com/Semantic-Org/Semantic-UI-LESS/blob/master/package.js#L44) where we should have 

```javascript
api.use('less', 'client');
```

usually before `api.addFiles`.

**Comment by splendido** [comment]
A small discrepancy also within packages' name. Components come with the `(official)' while the main two don't.

For example:
* Semantic UI - LESS Release of Semantic UI
* Semantic UI - Checkbox **(official)**: Single component release of checkbox

lets choose whether to keep *(official)* or not....

**Comment by jlukic** [comment]
I'll remove official from components. No need to keep

**Comment by splendido** [comment]
I'm testing the less version right now...
...I'm getting errors :(

> package.js:15:12: require is not defined

**Comment by jlukic** [comment]
I think i need to swap out `require` for `Npm.require` inside `package.js`

**Comment by splendido** [comment]
Just did it...

Now the error is

> package.js:24:22: __dirname is not defined

**Comment by splendido** [comment]
I'm not a big fan of this files walk...

Also in case you'll get it working, to my best knowledge, you won't be able to use the package locally after a git clone. In this case the cwd will be the meteor project root folder and not the root folder of the package...

But this might be a minor aspect

**Comment by jlukic** [comment]
Can you try replacing `__dirname` with `process.env.cwd` looks like `__dirname`  constant is not available in meteor

**Comment by jlukic** [comment]
Apparently ``__dirname` node constant isn't available in meteor. Quick google says ``path.resolve('.');`` should work.

**Comment by splendido** [comment]
I got it working with `process.cwd()` and (after having added a console log to see which files are being added) I get this log:

```
Adding the following files:                  \
[ 'test-semantic-ui/.gitignore',
  'test-semantic-ui/.meteor/.finished-upgraders',
  'test-semantic-ui/.meteor/.gitignore',
  'test-semantic-ui/.meteor/.id',
  'test-semantic-ui/.meteor/cordova-plugins',
  'test-semantic-ui/.meteor/local/build/README',
  'test-semantic-ui/.meteor/local/build/main.js',
  'test-semantic-ui/.meteor/local/build/programs/server/app/lib/config/accounts_t9n.js',
  'test-semantic-ui/.meteor/local/build/programs/server/app/lib/config/at_config.js',
  
  ...

  'test-semantic-ui/.meteor/local/build/programs/server/packages/nooitaf_semantic-ui.js',
  'test-semantic-ui/.meteor/local/build/programs/server/packages/nooitaf_semantic-ui.js.map',
  'test-semantic-ui/.meteor/local/build/programs/server/packages/npm-bcrypt.js',
  'test-semantic-ui/.meteor/local/build/programs/server/packages/npm-bcrypt.js.map',
  'test-semantic-ui/.meteor/local/isopacks/useraccounts_semantic-ui/web.browser/packages/useraccounts:semantic-ui.js.map',
  'test-semantic-ui/.meteor/local/isopacks/useraccounts_semantic-ui/web.browser.json',
  'test-semantic-ui/.meteor/local/shell-history',
  'test-semantic-ui/.meteor/local/shell.sock',
  'test-semantic-ui/.meteor/packages',
  'test-semantic-ui/.meteor/platforms',
  'test-semantic-ui/.meteor/release',
  'test-semantic-ui/.meteor/versions',
  'test-semantic-ui/client/footer.html',
  ...
  'test-semantic-ui/client/stylesheets/style.less',
  'test-semantic-ui/client/views/home.html',
  'test-semantic-ui/client/views/private.html',
  'test-semantic-ui/lib/config/accounts_t9n.js',
  'test-semantic-ui/lib/config/at_config.js',
  'test-semantic-ui/lib/router.js',
  'test-semantic-ui/packages/Semantic-UI-LESS/.git/HEAD',
  'test-semantic-ui/packages/Semantic-UI-LESS/.git/config',
  'test-semantic-ui/packages/Semantic-UI-LESS/.git/description',
  'test-semantic-ui/packages/Semantic-UI-LESS/.git/hooks/applypatch-msg.sample',
  'test-semantic-ui/packages/Semantic-UI-LESS/.git/hooks/commit-msg.sample',
  'test-semantic-ui/packages/Semantic-UI-LESS/.git/hooks/post-update.sample',
  'test-semantic-ui/packages/Semantic-UI-LESS/.git/hooks/pre-applypatch.sample',
  'test-semantic-ui/packages/Semantic-UI-LESS/.git/hooks/pre-commit.sample',
  ...
  'test-semantic-ui/packages/Semantic-UI-LESS/.git/objects/pack/pack-51c416b763525237fcac2c4204aa7ebb1cd2478c.idx',
  'test-semantic-ui/packages/Semantic-UI-LESS/.git/objects/pack/pack-51c416b763525237fcac2c4204aa7ebb1cd2478c.pack',
  'test-semantic-ui/packages/Semantic-UI-LESS/.git/packed-refs',
  'test-semantic-ui/packages/Semantic-UI-LESS/.git/refs/heads/master',
  'test-semantic-ui/packages/Semantic-UI-LESS/.git/refs/remotes/origin/HEAD',
  'test-semantic-ui/packages/Semantic-UI-LESS/.gitignore',
  'test-semantic-ui/packages/Semantic-UI-LESS/LICENSE',
  'test-semantic-ui/packages/Semantic-UI-LESS/README.md',
  'test-semantic-ui/packages/Semantic-UI-LESS/_site/collections/breadcrumb.overrides',
  'test-semantic-ui/packages/Semantic-UI-LESS/_site/collections/breadcrumb.variables',
  ...
  'test-semantic-ui/packages/Semantic-UI-LESS/_site/collections/menu.overrides',
  'test-semantic-ui/packages/Semantic-UI-LESS/_site/collections/menu.variables',
  'test-semantic-ui/packages/Semantic-UI-LESS/_site/collections/message.overrides',
  'test-semantic-ui/packages/Semantic-UI-LESS/_site/collections/message.variables',
  'test-semantic-ui/packages/Semantic-UI-LESS/_site/collections/table.overrides',
  ...
  'test-semantic-ui/packages/Semantic-UI-LESS/_site/modules/video.variables',
  'test-semantic-ui/packages/Semantic-UI-LESS/_site/views/ad.overrides',
  'test-semantic-ui/packages/Semantic-UI-LESS/_site/views/ad.variables',
  'test-semantic-ui/packages/Semantic-UI-LESS/_site/views/card.overrides',
  'test-semantic-ui/packages/Semantic-UI-LESS/_site/views/card.variables',

  ...

  'test-semantic-ui/packages/Semantic-UI-LESS/definitions/views/statistic.less',
  'test-semantic-ui/packages/Semantic-UI-LESS/package.js',
  'test-semantic-ui/packages/Semantic-UI-LESS/package.json',
  'test-semantic-ui/packages/Semantic-UI-LESS/theme.config.example',
  'test-semantic-ui/packages/Semantic-UI-LESS/themes/amazon/elements/button.overrides',
  'test-semantic-ui/packages/Semantic-UI-LESS/themes/amazon/elements/button.variables',
  'test-semantic-ui/packages/Semantic-UI-LESS/themes/basic/assets/fonts/icons.eot',
  'test-semantic-ui/packages/Semantic-UI-LESS/themes/basic/assets/fonts/icons.svg',
  'test-semantic-ui/packages/Semantic-UI-LESS/themes/basic/assets/fonts/icons.ttf',

  ...
  
  'test-semantic-ui/packages/Semantic-UI-LESS/themes/twitter/elements/button.overrides',
  'test-semantic-ui/packages/Semantic-UI-LESS/themes/twitter/elements/button.variables',
  'test-semantic-ui/public/imgs/bg.jpg',
  'test-semantic-ui/server/lib/config/accounts.js',
  'test-semantic-ui/server/lib/config/email.js' ]
 => Errors while adding packages:             

While building package semantic:ui:
error: File not found: test-semantic-ui/.meteor/local/build/programs/server/node_modules
error: File not found: test-semantic-ui/.meteor/local/build/programs/server/npm/ddp/node_modules
error: File not found: test-semantic-ui/.meteor/local/build/programs/server/npm/email/node_modules
error: File not found: test-semantic-ui/.meteor/local/build/programs/server/npm/http/node_modules
error: File not found: test-semantic-ui/.meteor/local/build/programs/server/npm/iron:router/node_modules
error: File not found: test-semantic-ui/.meteor/local/build/programs/server/npm/logging/node_modules
error: File not found: test-semantic-ui/.meteor/local/build/programs/server/npm/minifiers/node_modules
error: File not found: test-semantic-ui/.meteor/local/build/programs/server/npm/mongo/node_modules
error: File not found: test-semantic-ui/.meteor/local/build/programs/server/npm/npm-bcrypt/node_modules
error: File not found: test-semantic-ui/.meteor/local/build/programs/server/npm/webapp/node_modules
test-semantic-ui/packages/Semantic-UI-LESS/definitions/collections/breadcrumb.less:19:1: Less compiler error: '../../theme.config' wasn't found
test-semantic-ui/packages/Semantic-UI-LESS/definitions/collections/form.less:19:1: Less compiler error: '../../theme.config' wasn't found
test-semantic-ui/packages/Semantic-UI-LESS/definitions/collections/grid.less:19:1: Less compiler error: '../../theme.config' wasn't found

...

test-semantic-ui/packages/Semantic-UI-LESS/definitions/views/feed.less:19:1: Less compiler error: '../../theme.config' wasn't found
test-semantic-ui/packages/Semantic-UI-LESS/definitions/views/item.less:19:1: Less compiler error: '../../theme.config' wasn't found
test-semantic-ui/packages/Semantic-UI-LESS/definitions/views/statistic.less:19:1: Less compiler error: '../../theme.config' wasn't found
```

**Comment by splendido** [comment]
I'll try the alternatives you're suggesting, but this is exactly what I had in mind: the `cwd` is the project's path and not the package's path.

I'll also try a *fake* publish to see wheter in that case it works...

**Comment by splendido** [comment]
Same result with `path.resolve('.');`...

**Comment by jlukic** [comment]
Yeah apparently there are a lot of dotfiles added to meteor packages. Man i  really wish they made it easier to do this.

**Comment by splendido** [comment]
I see...
But this is the reason why I wanted to create the list of files to be added within a gulp task ;-)


Also `theme.config.example` -> `theme.config`

now the less compiler is complaining about a missing `theme.less`

**Comment by jlukic** [comment]
After downloading less you need to install which requires a couple renames. https://github.com/Semantic-Org/Semantic-UI/tree/master/src#importing-less

**Comment by splendido** [comment]
Ok, the (partially) good news is that when running `meteor publish` from the package folder the files walk picks up only the files present there!

...including `.git/*`, `.gitignore`, `README.md`, etc.
But I guess initializing the walk from the three subfolders `_site`, `definitions`, `themes` would be enough to solve this!

**Comment by splendido** [comment]
I'm aware of the *theming* workflow... but that's another story.

When you run `meteor publish` the package is bundled first and then uploaded to the *packages server*.
This means all `.less` files are compiled too

**Comment by splendido** [comment]
there's no `theme.less` inside the repo...

**Comment by splendido** [comment]
there's also a typo inside `package.js` for both main repos:

`'clent'` ->  `'client'`  on last line

**Comment by splendido** [comment]
Ok I have a (probably) working `package.js` version for `semantic:ui-css`:

```javascript
Package.describe({
  name    : 'semantic:ui-css',
  summary : 'Semantic UI - CSS Release of Semantic UI',
  version : '1.9.2',
  git     : 'git://github.com/Semantic-Org/Semantic-UI-CSS.git',
});

Package.onUse(function(api) {
  var
    fs   = Npm.require('fs'),
    path = Npm.require('path'),
    files,
    walk
  ;

  // recursive sync walk
  walk = function(dir) {
    var
      list  = fs.readdirSync(dir),
      files = []
    ;

    list.forEach(function(file) {
      var
        filePath = path.join(dir, file),
        stat     = fs.statSync(filePath)
      ;

      if(stat && stat.isDirectory()) {
        files = files.concat(walk(filePath));
      }
      else {
        files.push(filePath);
      }
    });
    return files;
  };
  files = walk('./components/');
  files.push.apply(files, walk('./themes/'));

  api.versionsFrom('1.0');
  api.addFiles(files, 'client');
});
```

In case, we could point to the `README.md` of the main SUI repo by changing the package description with this:

```
Package.describe({
  name    : 'semantic:ui-css',
  summary : 'Semantic UI - CSS Release of Semantic UI',
  version : '1.9.2',
  git     : 'git://github.com/Semantic-Org/Semantic-UI-CSS.git',
  documentation: "https://github.com/Semantic-Org/Semantic-UI/blob/master/README.md",
});
```

**Comment by splendido** [comment]
As expected, the above `package.js` doesn't work if you try to use it as a local pacakge :(

**Comment by splendido** [comment]
For the LESS version something like this is getting the correct list of files:

```javascript
var
  where = 'client' // Adds files only to the client
;

Package.describe({
  name    : 'semantic:ui',
  summary : 'Semantic UI - LESS Release of Semantic UI',
  version : '1.9.2',
  git     : 'git://github.com/Semantic-Org/Semantic-UI-LESS.git',
});

Package.onUse(function(api) {
  var
    fs   = Npm.require('fs'),
    path = Npm.require('path'),
    files,
    walk
  ;

  // recursive sync walk
  walk = function(dir) {
    var
      list,
      files = []
    ;

    try {
      list = fs.readdirSync(dir);
    } catch (err) {
      return files;
    }

    list.forEach(function(file) {
      var
        filePath = path.join(dir, file),
        stat     = fs.statSync(filePath)
      ;

      if(stat && stat.isDirectory()) {
        files = files.concat(walk(filePath));
      }
      else {
        files.push(filePath);
      }
    });
    return files;
  };
  files = walk('./_site/');
  files.push.apply(files, walk('./definitions/'));
  files.push.apply(files, walk('./themes/'));

  api.versionsFrom('1.0');
  api.addFiles(files, 'client');
});
```

But I cannot test it unless I actually publish it.
I might publish a `0.0.0.rc1` version though :-)

**Comment by splendido** [comment]
Going to dinner now...
Talk to you later!

**Comment by jlukic** [comment]
Thanks for your help. Will get back to you

**Comment by jlukic** [comment]
I moved over the whole thing to the `gulpfile`. I think you are correct in that dealing with node inside of meteor's `package.js` is a little unwieldy.

Will try publishing shortly

**Comment by splendido** [comment]
...for the CSS version, isn't it enough to add `semantic.css`, `semantic.js` plus the `assets/**` files?
Having the whole list of source components won't be wrong but perhaps a bit overkilling?

**Comment by splendido** [comment]
Within the main SUI repo [README.md](https://github.com/Semantic-Org/Semantic-UI/blob/master/README.md) the referenced package name name is wrong:


[Meteor](https://www.meteor.com/) | `meteor add semantic-org:semantic-ui` | 

should be changed to

|Environment | Install Script | Repo |
|--- | --- | --- | 
|[Meteor](https://www.meteor.com/) - CSS Only | `meteor add semantic:ui-css` | [CSS Repo](https://github.com/Semantic-Org/Semantic-UI-CSS) |
|[Meteor](https://www.meteor.com/) - [LESS](https://github.com/less/less.js/) Only | `meteor add semantic:ui-css` | [LESS Repo](https://github.com/Semantic-Org/Semantic-UI-LESS) |

**Comment by jlukic** [comment]
Fixing

**Comment by jlukic** [comment]
> ...for the CSS version, isn't it enough to add semantic.css, semantic.js plus the assets/** files?
Having the whole list of source components won't be wrong but perhaps a bit overkilling?

I prefer to include individual components, the whole concatenated release is going to get monstrously large as I continue to add components.

**Comment by splendido** [comment]
:+1:

**Comment by splendido** [comment]
I successfully tried the css version.

But the LESS one is not working even with a *static* `package.js` file...
I'd say there's still a bit of work to do for this to work :(

What if you remove the `pacakge.js` file from the LESS repository and you'll launch it we it will be ready?



I'm sorry this integration is taking so much of your time!
But the Meteor community will truly appreciate all these efforts!


Tanks in advance!

**Comment by jlukic** [comment]
> What if you remove the pacakge.js file from the LESS repository and you'll launch it we it will be ready?

Could you explain this in other words, im not sure i understand.

I think there also might be a bug with trying to immediately publish a release to github after pushing files in the admin scripts. It appears to be tagging the **previous** commit  as the current release. Perhaps it should wait 5-10 seconds after pushing.

**Comment by splendido** [comment]
crap, I forgot to add `meteorpublish` to the `semantic` organization....
All biulds for the new release on autopublish.meteor.com just went errored :(

I'll fix it right now!

**Comment by splendido** [comment]
> What if you remove the pacakge.js file from the LESS repository and you'll launch it we it will be ready?

I wanted to say that since the LESS package is not going to work as it is now, I'd say it would be better to remove the `package.js` file from the repo not to sell it as already working (and to prevent autopublish.meteor.com to publish it in its current status...).

But feel free to leave it there, perhaps just un-toggle `semantic:ui` form autopublish.meteor.com

**Comment by splendido** [comment]
is it me, or you're calling `tagFiles` twice?
See [these lines](https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/admin/distributions/update.js#L147-149)

**Comment by splendido** [comment]
on the CSS repo there are too much files being added, see [here](https://github.com/Semantic-Org/Semantic-UI-CSS/blob/master/package.js#L17-18) and [here](https://github.com/Semantic-Org/Semantic-UI-CSS/blob/master/package.js#L149-152)!

The second block is potentially harmful! :(

**Comment by jlukic** [comment]
So in meteor, add file includes these files on every page? Or exposes them to be included?

**Comment by splendido** [comment]
the list of files you provide with `addFiles` is compiled and bundled with the ISOBuild system to be uploaded to the package server.

Adding things three times will create a triple weighted bundle at least...

**Comment by jlukic** [comment]
So not understanding what these APIs are hooked up to, should it just be including `semantic.css` and `semantic.js` then? How will people bundle components then?

**Comment by splendido** [comment]
It's not that easy to explain, there's a dedicated part of the meteor platform called [IsoBuild](https://www.meteor.com/isobuild) that creates package bundles.

All files that you *add* before the package is created are compiled (for less, coffeescritp, jade, etc...), bundled all together.

When you add a package to your app the very same files are made available in a transparent way so that when you bundle your app for deployment you end up with a single minified/uglified js file including code and html templates compiled into javascirpt functions, plus a css file including all imported styles.

**Comment by splendido** [comment]
Adding only `semantic.css` and `semantic.js` would make the file list shorter for sure but there will no difference in the end ;-)

**Comment by jlukic** [comment]
So I've just added `semantic.css` and `semantic.js` to `css` build and removed the readme and license.

**Comment by jlukic** [comment]
If everything sounds fine to you i'll run the scripts to publish

**Comment by splendido** [comment]
you mean creating a `1.9.4` release?

**Comment by jlukic** [comment]
I could do that, let me stage it real quick

**Comment by splendido** [comment]
if you're going for a `1.9.4` I'm not going to retrigger the publishes for `1.9.3` (which is what I'm trying to do right now...).

Just let me know what you prefer

**Comment by jlukic** [comment]
oh i'd prefer to keep same version if they allow republishing (npm does not)

**Comment by splendido** [comment]
There's nothing published on Meteor right now...
...my fault: I forgot to add the `meteorpublish` user (the one I'm using on autopublish.meteor.com) to the `semantic` org so all publish attempts went errored.

Could you re-create the release on the repos?

**Comment by jlukic** [comment]
I republished `1.9.3` for less and css on github

**Comment by jlukic** [comment]
https://www.youtube.com/watch?v=O_CoY0sBb1M

**Comment by splendido** [comment]
What's that?! :-)

`semantic:ui-css` correctly  autopublished! Hooray!!!  :-D

**Comment by jlukic** [comment]
Ok I think i'm going to head home from the office then. Mission accomplished. Now to write a damn newsletter...

**Comment by splendido** [comment]
I'm going to re-trigger the single components then...

**Comment by splendido** [comment]
Yeah, mission accomplished!

Thanks a lot!

I think we'll read about this in more than one place ;-)
Well done, awesome work!!!

**Comment by gabormeszoly** [comment]
:) Pusher Robot

**Comment by jlukic** [comment]
The single components will have to wait to be retagged with `1.9.4`, no simple way for me to automate deleting tags across all the repos

**Comment by splendido** [comment]
Ok, so we have some inconsistent versioning now: see [autopublish.meteor.com](https://autopublish.meteor.com).

I didn't understand it, sorry!
...but this shoudn't be a big problem, at the next release everything will be fixed!


Just lets see how to proceed to get also the LESS version working.
I'll try to ping nemo64 to whether he's available to help or not.


Thanks again and sorry for the little mess.

Cheers,
Luca

**Comment by splendido** [comment]
Red Alarm!!!
for `semantic:ui-css` all assets are missing: see [these lines]

**Comment by jlukic** [comment]
It looks like your last comment is missing a link. I wanted to resolve Meteor packages today. What do I need to do?

**Comment by splendido** [comment]
yeah, sorry :(
just updated...

The package `semantic:ui-css` is correctly including `js` and `css` sources but is missing all the assets!

**Comment by jlukic** [comment]
I'm going to try to release a new minor version, I think the tagging issue should be fixed.

**Comment by splendido** [comment]
fingers crossed ;-)

**Comment by jlukic** [comment]
Looks like it didn't hit the mark. I think I will need to manually specify the commit-ish when creating the release, with something like `git rev-parse --verify HEAD` because GitHub APIs seems not to grab the correct value, if you create a release a few seconds after pushing it.

**Comment by splendido** [comment]
...also some `1.10.0 tag was attached to acutal `1.9.3` release :(
I'm sorry I can be of little help with this.

On the other side, it's being a strong load test for `autopublish.meteor.com`: I had some *timeout* and *disconnection* I need to deal with, possibly adding delayed retrials...

**Comment by jlukic** [comment]
So it looks like the sweet spot is a 2 second delay after push before tagging a release, otherwise it tags the wrong release. Now my build scripts all slow. Booo

**Comment by splendido** [comment]
Ok, it seems you managed to get it right!
all versions 1.10.2 were correctly tagged and published :+1: 

I've also updated the [organization info on Atmosphere](https://atmospherejs.com/semantic)

**Comment by splendido** [comment]
Another problem: [this line](https://github.com/Semantic-Org/Semantic-UI-CSS/blob/master/package.js#L24) should be removed.

No need for a new release, I'll publish the package by hands with version 1.10.2.1.

**Comment by oliverlloyd** [comment]
`semantic:ui-css` works well for me. Thank you both for all your work on this, it's appreciated.

**Comment by GitYong** [comment]
Nicely done! BTW, how to write a less override file for this package?

**Comment by oliverlloyd** [comment]
@GitYong You might want to follow [this issue](https://github.com/Semantic-Org/Semantic-UI-LESS/issues/1) - this package is purely the css without overrides or theming.

**Comment by GitYong** [comment]
@oliverlloyd Thanks! I made it.

**Comment by devlinpadayachee** [comment]
Anyway we can get the latest version of semantic into Meteor

**Pull request merged**
