### PR TITLE
[Dropdown] Display sub menu on the left when if cannot fit screen

### PR DESCRIPTION
**Pull request by Graveheart**
Fixes issue #4112

---

This change is [Reviewable](https://reviewable.io/reviews/semantic-org/semantic-ui/4211)

### CODE REVIEW

**Comment by jlukic** [comment]
Looks good, I'll try to review sometime soon.

**Comment by Graveheart** [comment]
Cool, that would be great

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/semantic-org/semantic-ui/4211#-:-KNqsETcrTxQkgp3nW9m:1703186898)*

**Comment by s-devaney** [comment]
LGTM

**Comment by andreiho** [comment]
@jlukic Any updates on this? Can we expect it included in a release anytime soon?

**Comment by jlukic** [comment]
In my testing it appeared after `leftward` was set it would reset to rightward on every other open because it would then pass the `is.fitWidth` (now `can.openRightward) function. 

I've fixed this, and also modified the css to move the pointer with `pointing dropdown menu` when opening leftward

**Comment by andreiho** [comment]
@jlukic Thanks.

**Pull request merged**
