### PR TITLE
fix: add less dependency for pnpm installs

### PR DESCRIPTION
**Pull request by DanielRuf**
✖ Multiple features in one PR
✖ New Components Unless Previously Discussed with Maintainers (Consider creating separate repo, I'll link out to you)

✔ Add comments to complex/confusing code in "code" view of PR
✔ BUGS → This form is required:
✔ Enhancements → Only specific enhancements with detailed descriptions.

### Issue Titles

[dependencies] add less dependency for pnpm

### Closed Issues
#6706 

### Description
pnpm does and can not resolve dynamic require's

### Testcase

`pnpm i semantic-ui`

### CODE REVIEW

**Comment by DanielRuf** [comment]
You have to change the package.json of the `semantic-ui` package.
Also make sure to run `pnpm install` in `/home/cdfa/Projects/static-sticky/node_modules/.registry.npmjs.org/semantic-ui` or your folder.

**Comment by DanielRuf** [comment]
I've done

```
pnpm i semantic-ui
cd /Users/druf/projects/pnpm-semantic-ui-test/node_modules/
cd semantic-ui
apply the changes
pnpm i
```

Or we could add it as peerdependency.

**Comment by DanielRuf** [comment]
I've done

```
pnpm i semantic-ui
cd /Users/druf/projects/pnpm-semantic-ui-test/node_modules/
cd semantic-ui
apply the changes
pnpm i
```

**Comment by cdfa** [comment]
Well, I installed your branch which includes the commit that adds less as a dependency and that did actually change something, because pnpm downloaded a new package. When this branch gets merged, people are just going to install it like i did, so not expecting any special setup. We should try to make it work that way too.

AFAIK, package's dependencies don't get installed in their respective 'node_modules' directories, but in the directory above (the user's application's `node_modules` directory), which is different from what you would get when running `pnpm i` in `node_modules/semantic-ui`.

**Comment by DanielRuf** [comment]
Well, `gulp-less` already has `less` as dependency. `semantic-ui` too. So the issue is still `accord` I think as the dynamic require is still an issue.

I'll test further and maybe we have to fork `accord` or add some script or setting for pnpm.

**Comment by DanielRuf** [comment]
https://github.com/pnpm/pnpm/issues/949

**Comment by DanielRuf** [comment]
I've updated the PR.

**Comment by cdfa** [comment]
I still get the same error...
Remember to use `pnpm i --force` to recreate the `node_modules` directory to clean any less package you might have installed otherwise.

**Comment by DanielRuf** [comment]
Ah sorry, it is probably just used by the install command but not when it is part of a package.

cc @zkochan

**Comment by DanielRuf** [comment]
> I still get the same error...
> Remember to use `pnpm i --force` to recreate the `node_modules` directory to clean any less package you might have installed otherwise.

I always create a new testfolder for local testing ;-)

**Comment by DanielRuf** [comment]
> Ah sorry, it is probably just used by the install command but not when it is part of a package.

Ah yes it is.

**Comment by DanielRuf** [comment]
Please try ```
module.exports = {
    hooks: {
        readPackage
    }
}

 function readPackage(pkg) {
    if (pkg.name === 'accord') {
        pkg.dependencies = Object.assign(
            {},
            pkg.dependencies,
            {less: '*'}
        )
    }
    return pkg
}
```

as pnpmfile.js in your project folder before installing / saving semantic-ui.

**Comment by DanielRuf** [comment]
```
pnpm install git://github.com/DanielRuf/Semantic-UI.git#fix/add-less-for-pnpm --save
Using hooks from: /Users/druf/projects/pnpm-test-4/pnpmfile.js
readPackage hook is declared. Manifests of dependencies might get overridden
Packages: +657
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 657, reused 657, downloaded 0, done
node_modules/.registry.npmjs.org/fsevents/1.2.4/node_modules/fsevents: Running install script, done in 357ms
node_modules/.github.com/DanielRuf/Semantic-UI/42dabde159bcac8c81d9dfee54d92baa0e32760f/node_modules/semantic-ui: Running install script, done in 2s
```

**Comment by DanielRuf** [comment]
So my change is not needed. It is a change which is required at the level of `accord`.

I'll create a repo with the config.

**Comment by DanielRuf** [comment]
https://github.com/DanielRuf/pnpmfiles/blob/master/semantic-ui/pnpmfile.js

**Comment by cdfa** [comment]
It seems adding `less` as dev dependency as suggested [here](https://github.com/pnpm/pnpm/issues/762) also works, which seems like a better solution to me. Thanks for helping anyway!

**Comment by ndc411** [comment]
first, i used gulp-less 4.x, but error was showm. then downgrade to 3.x,it works normally!

npm install --save gulp-less@3.5.0

**Pull request closed without merging**
