### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by avalanche1**
following a hot scent..)

### CODE REVIEW

**Comment by avalanche1** [comment]
Can you re-merge this?

**Comment by jlukic** [comment]
added back.

**Comment by avalanche1** [comment]
No, still not there.

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI#usage-questions

**Comment by avalanche1** [comment]
It would be better in https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md

**Pull request merged**
