### PR TITLE
Use '===' comparison

### PR DESCRIPTION
**Pull request by dijonkitchen**
Found via [HoundCI](https://houndci.com/)'s error I get after a `gulp build`.

### CODE REVIEW

**Comment by dijonkitchen** [comment]
I think this is still relevant!

**Comment by dijonkitchen** [comment]
Can this be merged? It's still relevant.

**Comment by brodybits** [comment]
??

**Comment by dijonkitchen** [comment]
@jlukic ?

**Comment by jlukic** [comment]
@dijonkitchen 

This PR breaks the functionality of the rules you've modified. 

Values are specified like `minLength[1]` and then split into `minLength` and `1` via regex, see `get.ancillaryValue` below for how this is parsed.

```javascript
ancillaryValue: function(rule) {
  if(!rule.type || (!rule.value && !module.is.bracketedRule(rule))) {
    return false;
  }
  return (rule.value !== undefined)
    ? rule.value
    : rule.type.match(settings.regExp.bracket)[1] + ''
  ;
},
```

Using `===` comparison would cause the rules conditions to never be run. 

---------------------

@dreaming-augustin Please be mindful of your tone. It's not appropriate to tag onto PRs to share negative feedback about the project.

**Pull request closed without merging**
