### PR TITLE
Updated FontAwesome with complete port of FA5

### PR DESCRIPTION
**Pull request by hammy2899**
Added sui aliases for current icons
Added new aliases for old icons which no longer exist to help with compatibility

I have tried my best to add this with the best compatibility as I can, I have found a couple bugs with a few icons not displaying the correct icon and I am going to repair these in the next few days apart from that the icons work perfectly.

I have also created the docs page and have also created a pull request https://github.com/Semantic-Org/Semantic-UI-Docs/pull/378

### CODE REVIEW

**Comment by jlukic** [comment]
Thanks, this might take a bit to evaluate, but is definitely a high priority.

**Comment by hammy2899** [comment]
@davidpanzarella There are still a few bugs which I am currently working on and like Jack said this will take sometime to look through also Jack seems to be quite busy right now, take a look at this discussion for some more details https://github.com/Semantic-Org/Semantic-UI/issues/6109#issuecomment-361104864

**Comment by GuacheSuede** [comment]
@hammy2899 I will take a look at this after the discussion with Jack

**Comment by hammy2899** [comment]
I have fixed all the broken icons by manually going through and checking them. I have also added the new icons added in FA 5.0.3 and 5.0.5.

Here is a list of all the stuff I have changed/fixed:
Added `elementor` icon
Added `youtube-square` icon
Added `window-minimize` icon
Added `chess` icon
Added `chess bishop` icon
Added `chess board` icon
Added `chess king` icon
Added `chess knight` icon
Added `chess pawn` icon
Added `chess queen` icon
Added `chess rock` icon
Added `square full` icon
Added `baseball ball` icon
Added `basketball ball` icon
Added `bowling ball` icon
Added `football ball` icon
Added `futbol` icon
Added `futbol outline` icon
Added `golf ball` icon
Added `hocky puck` icon
Added `quidditch` icon
Added `table tennis` icon
Added `volleyball ball` icon
Fixed `cloud download alternate` icon
Fixed `cloud upload alternate` icon
Fixed `external link square alternate` icon
Fixed `pencil alternate` icon
Fixed `window close` icon
Fixed `window restore outline` icon
Fixed `images` icon
Fixed `500px` icon
Fixed `accessible icon` icon
Fixed `accusoft` icon
Fixed `app store ios` icon
Fixed `apper` icon
Fixed `asymmetrik` icon
Fixed `audible` icon
Fixed `avianex` icon
Fixed `aws` icon
Fixed `bimobject` icon
Fixed `bitcoin` icon
Fixed `centercode` icon
Fixed `cloudscale` icon
Fixed `cloudsmith` icon
Fixed `cloudversify` icon
Fixed `cpanel` icon
Fixed `digital ocean` icon
Fixed `discord` icon
Fixed `discourse` icon
Fixed `dochub` icon
Fixed `docker` icon
Fixed `draft2digital` icon
Fixed `dribbble square` icon
Fixed `dyalog` icon
Fixed `fly` icon
Fixed `uber` icon
Fixed `uikit` icon
Fixed `uniregistry` icon
Fixed `untappd` icon
Fixed `ussunnah` icon
Fixed `vaadin` icon
Fixed `viber` icon
Fixed `wordpress simple` icon
Fixed `xbox` icon
Fixed `yandex international` icon
Fixed `yandex` icon
Renamed `list ol` to `ordered list`
Renamed `list ul` to `unordered list`
Renamed `user md` to `user doctor`
Renamed `cc amex` to `credit card american express`
Renamed `cc *` to `credit card *`
Renamed `red river` to `redriver`

**Comment by c01gat3** [comment]
Is this going to support the FA pro version with solid, regular & light weights?

**Comment by hammy2899** [comment]
@c01gat I have thought about this for a while now but I can't think of away of implementing it without leaking the pro version.

The only way I can think of which would possibly work is creating the CSS but making the user generate the icon font files with a cli tool or something.

**Comment by jlukic** [comment]
@hammy2899 it looks like there quite a few duplicates in `icon.overrides` for example, `eraser` appears 6 times. 

I'm going to try to dedupe the list then port over to docs.

**Comment by jlukic** [comment]
Fixed dupes in https://github.com/Semantic-Org/Semantic-UI/commit/1587c0be7e71193f6ec054fc6e6d026f1ce58939?w=1

**Comment by hammy2899** [comment]
@jlukic I did but I don't have it to hand anymore. If you want I can probably write it again.

**Comment by c01gat3** [comment]
`cloud download alternate` & `cloud upload alternate`

Did these need the `alternate` class?
They no longer match with the old icons.

screen shot 2018-02-21 at 2 10 11 pm

**Comment by magiksd** [comment]
Hello, there is a conflict between "file image outline" and "image outline" that cause the "file" version to appear the same

**Comment by hammy2899** [comment]
@c01gat3 They both have `alternate` because that's what they are in FA5. There's aliases setup for `cloud.download` and `cloud.upload`

@magiksd Thanks for letting us know, I will add a fix to the PR I created last night if I get time today.

**Comment by dschu-lab** [comment]
I'm currently using `"semantic-ui-react": "^0.79.0",` in combination with the semantic.min.css file of `2.3.1`, even though the [docs still refering to 2.2.12](https://react.semantic-ui.com/usage).

When using an icon introduced in Fontawesome 5.0 like `<Icon name='chess' />`, the correct icon is shown, but a warning is printed out in the console:
```
Warning: Failed prop type: Invalid prop `name` of value `chess` supplied to `Icon`.

Instead of `chess`, did you mean:
  - check
  - chain
  - chat
```

Is this supposed to work right now? Again, [the docs](https://react.semantic-ui.com/elements/icon) only mention Font Awesome 4.7.0.

**Comment by hammy2899** [comment]
@dschu-lab This is because SUI react isn't updated yet with the new icons. See https://github.com/Semantic-Org/Semantic-UI-React/blob/f51367f7268e844809c8e7d9c226fed9c38a958f/src/index.d.ts#L88

@Semantic-Org/react-maintainers

**Pull request closed without merging**
