### PR TITLE
Semantic UI Calendar Module

### LINKED ISSUE #191: [UI] Date Picker
Please include a datepicker component. If you have no idea what I'm saying, please see this link
http://jqueryui.com/datepicker/

### PR DESCRIPTION
**Pull request by nhodges**
This pull request is currently a WIP and should not be merged, treat it as a RFC.

Preview: http://codepen.io/nuri/pen/yNLZOd

Closes #191.

### CODE REVIEW

**Comment by jlukic** [comment]
You might find these links useful

https://github.com/Semantic-Org/Semantic-UI-Docs/blob/1.0/spec/module.commented.js
https://github.com/Semantic-Org/Semantic-UI-Docs/blob/1.0/spec/modal.commented.js

They are a little old but give some perspective on the module format.

**Comment by kvetoslavnovak** [comment]
Great start! I guess eventually shall this work as a datepicker as well?

**Comment by jlukic** [comment]
I've added an online repo where I'll try to keep notes on SUI module format
https://github.com/Semantic-Org/Module-Examples

You can see the annotated source of current version here
http://semantic-org.github.io/Module-Examples/docs/module.html

**Comment by nhodges** [comment]
Awesome, @jlukic thanks for updating that and publishing to its own repo! Looks like I ended up stripping out part of what's suggested in the pattern. :) Will take a more in-depth read this evening.

@kvetoslavnovak That's correct, datepicker part is coming next now that I have the rendering bit down.

**Comment by kvetoslavnovak** [comment]
Hi nhodges, is there anything new? Do you need help with testing?

**Comment by humanitiesNerd** [comment]
Is there anything going on here ? Can I help in any way ?

**Comment by jlukic** [comment]
Nothing official going on with calendars yet.

**Comment by vernard** [comment]
+1

**Comment by SrPatinhas** [comment]
Maybe close this one as we can see there is this one #3256 more advanced? maybe if they want change some css @jlukic

**Comment by contactjavas** [comment]
Oh come on stale bot, don't auto-close good PR

**Pull request closed without merging**
