### PR TITLE
Fix i.icon selector with attribute

### PR DESCRIPTION
**Pull request by lolychee**

### CODE REVIEW

**Comment by victorpolko** [comment]
This commit is very important. Rails app's assets fail to compile with error:
```bash
Sass::SyntaxError: Invalid CSS after "...="top aligned"]": expected "{", was "i.icon,.ui.list..."

"i.icon" may only be used at the beginning of a compound selector.
```
We use bower so it's uneasy to rewrite this file manually.

Thank you, @lolychee

**Comment by jlukic** [comment]
I'll patch and release this today.

`1.7.0` will come tomorrow with new features.

**Comment by jlukic** [comment]
Please be careful with the current state of SUI in bower #1385

**Comment by jlukic** [comment]
Released.

**Comment by victorpolko** [comment]
@jlukic, thank you very much!
Unfortunately, I've ran into Asset Pipeline troubles with CSS (direct links to fonts in semantic.css, while AP uses fingerprinting) so that I fell back from Bower to Semantic-UI gem for now. Of course, I don't like it, but I need a fast working result now, so I decided to do so. I will watch your repo and will go back to Bower as soon as it will be working well.
Thanks again!

**Pull request merged**
