### PR TITLE
[Modal] Support modification of 'closable' setting while modal is open

### PR DESCRIPTION
**Pull request by mdehoog**
If the `closable` property of modal is modified while the modal is visible using `$('.ui.modal').modal('setting', 'closable', value);`, it does not take effect for mouse events until it is hidden and shown again. This is because the `closable` setting affects whether a click event is bound, rather than checking the setting in the click event handler itself.

Note that changing `closable` for a visible modal works for the escape key, because the key is checked in the event rather than a conditional binding.

This PR makes the behavior for click consistent with the escape behavior, by binding the click event whenever the modal is visible, and checking whether to close within the click handler itself. This means that the `closable` setting can be changed while the modal is visible.

### CODE REVIEW

**Comment by piya23300** [comment]
+1

**Comment by mdehoog** [comment]
Fixed merge conflicts, would really love this one to be merged. Thanks @jlukic

**Comment by lulalala** [comment]
Bump this, and can we mark this as a bug so it gets more attention?

**Comment by DornaHansen** [comment]
+1

**Comment by Jake-Lippert** [comment]
+1

**Comment by jlukic** [comment]
Merging with small modification

**Pull request merged**
