### PR TITLE
Update icons to support Font Awesome 4.3

### LINKED ISSUE #1642: Missing Font Awesome 4.3 icons
Semantic UI 1.7 is missing the new icons from Font Awesome 4.2 (now 4.3 which was released on Jan 22).

http://semantic-ui.com/elements/icon.html
http://fontawesome.io/whats-new/
https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.css

### PR DESCRIPTION
**Pull request by sergiopantoja**
Whew, this took a while. :stuck_out_tongue_closed_eyes: Let me know if you need any changes, or if there's another part of the codebase I need to update in addition to this.

Closes #1642 

Notes:

* The Font Awesome attribution/license banner was shortened here: https://github.com/FortAwesome/Font-Awesome/commit/6fbbefc89fa530c55a33bb5277d8b56ef27b3015
* `signal` and `wifi` are now two separate icons
* Added the `Gender` and `Payment Options` categories
* The `i.icon.plane` was repeated so I removed the second entry
* Font Awesome reference can be found [here](http://fontawesome.io/cheatsheet/) and [here](http://fontawesome.io/icons/)

### CODE REVIEW

**Comment by jlukic** [comment]
Thanks, having done all the original icons I know how much busy work this is. 

Will have to update the docs as well, will add commits to this PR

**Comment by jlukic** [comment]
Icons btw are sorted by hexcode to help make sure there are no duplicates, and to make it easier to see which icons were added last (highest hexcode values)

**Comment by jlukic** [comment]
Added docs https://github.com/Semantic-Org/Semantic-UI-Docs/commit/5f4a6c76464bab157d44701f5b45c8f8724a2c0c

**Comment by jlukic** [comment]
Available in `next`

**Comment by sergiopantoja** [comment]
Awesome! :+1:

> Icons btw are sorted by hexcode to help make sure there are no duplicates, and to make it easier to see which icons were added last (highest hexcode values)

Ah, gotcha. I'll keep this in mind for the next Font Awesome update.

**Pull request merged**
