### PR TITLE
Dropdown data cache

### PR DESCRIPTION
**Pull request by ascariandrea**
Hi, as for the pr #2308 there is a problem with the data cached values in the dropdown.
I didn't create a jsfiddle cause is the same bug of the other time, but this time in the dropdown.
Hope my contribution will be appreciated.

### CODE REVIEW

**Comment by jlukic** [comment]
I don't believe this is an issue with dropdown. 
http://jsfiddle.net/u44utsvn/

**Comment by ascariandrea** [comment]
I believe it is..
https://jsfiddle.net/50mps8mk/1/

**Comment by jlukic** [comment]
Thanks, I can see this is an issue when used with react.

**Comment by ascariandrea** [comment]
Happy to be helpful, you're welcome!

**Comment by jlukic** [comment]
Fiddle with `next` branch
https://jsfiddle.net/wodv1kep/

**Comment by jlukic** [comment]
@ascariandrea Thanks for your contribution. Feel free to continue to point out any issues with React integration, wanna make sure that's all straight.

**Pull request merged**
