### PR TITLE
Output css and js into seperate dist directories

### PR DESCRIPTION
**Pull request by kevindice**
#2413

### CODE REVIEW

**Comment by jlukic** [comment]
Hi, just need to make sure this works with legacy `semantic.json` file which do not contain an object for `css` and `js`.

Also a bit confused on use of `path.posix.join`

**Comment by kevindice** [comment]
Removed the .posix part and added a mechanism for gracefully continuing with a deprecation notice.

**Comment by jlukic** [comment]
Thanks, give me some time to review.

**Comment by kevindice** [comment]
Would it be better if this did not append /css and /js directories to the output paths of existing installations?

**Comment by jlukic** [comment]
Yes, that would be better. 


The install script should probably go 

* Different paths for js and css? (Yes/no)

If yes
* What path component js? 
* What path for component css?
* What path for concat js?
* What path for concat css?

If no, current questions.

**Pull request closed without merging**
