### PR TITLE
RTL Gulp Task

### PR DESCRIPTION
**Pull request by MohammadYounes**

### CODE REVIEW

**Comment by jlukic** [comment]
Added in 7b3919f789c1103d30e74250d7bde5497a8dd0bf 

I also added  an ``rtl watch`` task. 
4fa3100c5838456893e49dba2117a8ae10873147

You can run tasks with spaces in gulp like this 

```
gulp "watch rtl"
gulp "build rtl"
```

I will also add a value in ``semantic.json`` ``rtl: true`` which will run `rtl` tasks from ``gulp watch` and `gulp build`

**Comment by jlukic** [comment]
You can now run rtl tasks with `gulp build` and `gulp watch` when `semantic.json` has `rtl: true` ebda601

**Comment by jlukic** [comment]
I think this should be everything. Just need to confirm RTLCSS changes are correctly adjusting styles.

**Comment by MohammadYounes** [comment]
RTL task is based on release files, so its required to run after normal build.  also this https://github.com/Semantic-Org/Semantic-UI/commit/4fa3100c5838456893e49dba2117a8ae10873147#commitcomment-9190308

**Comment by jlukic** [comment]
Adding with `1.7.0`

**Pull request closed without merging**
