### PR TITLE
Add error formating for basic selects

### PR DESCRIPTION
**Pull request by davialexandre**

### CODE REVIEW

**Comment by jlukic** [comment]
Thanks for the pull request.

What's this rule?
```css
.ui.form .field.error select:focus { 
  -webkit-appearance: menulist-button;
}
```

**Comment by davialexandre** [comment]
This rule resets the select to its default appearance in webkit. I added it because of this other rule that sets the -webkit-appearance to none:

```css
.ui.form .field.error textarea:focus,
.ui.form .field.error select:focus,
.ui.form .field.error input:not([type]):focus,
.ui.form .field.error input[type="text"]:focus,
.ui.form .field.error input[type="email"]:focus,
.ui.form .field.error input[type="date"]:focus,
.ui.form .field.error input[type="datetime-local"]:focus,
.ui.form .field.error input[type="password"]:focus,
.ui.form .field.error input[type="number"]:focus,
.ui.form .field.error input[type="url"]:focus,
.ui.form .field.error input[type="tel"]:focus{
  background: @inputErrorFocusBackground;
  border-color: @inputErrorFocusBorder;
  color: @inputErrorFocusColor;

  -webkit-appearance: none;
  box-shadow: @inputErrorFocusBoxShadow;
}
```

I didn't want to repeat the background, border, color and box-shadow rules, so I thought that creating another rule just for the select appearance would be a better approach.

**Comment by davialexandre** [comment]
Here is an example of how the select is displayed without the rule http://jsfiddle.net/davialexandre/4tsLagt3/2/

**Comment by jlukic** [comment]
Merging this into `next`. Funny enough autoprefixer doesnt support [appearance](https://github.com/postcss/autoprefixer#why-doesnt-autoprefixer-support-appearance) so have to leave the `-webkit-` in the rules.

**Comment by jlukic** [comment]
Thanks for your patience with this.

**Pull request closed without merging**
