### PR TITLE
Email fix for #3755

### PR DESCRIPTION
**Pull request by ScopeyNZ**
In the end I did a bit of research and borrowed the [email regex used in angular.js](https://github.com/angular/angular.js/blob/4487d4a8a477ad440500e3574c141da48d13ab3d/src/ng/directive/input.js#L27).

### CODE REVIEW

**Comment by kevinresol** [comment]
Seems that this regexp is more accurate: 
```js
/^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i
```

Examples: http://try.haxe.org/#0B65c

**Comment by jlukic** [comment]
If it works for angular it works for me

 @kevinresol If you can qualify the differences in your regex I would consider.

**Comment by jlukic** [comment]
Added rlsnotes

**Comment by kevinresol** [comment]
@jlukic in the link I posted previously you can press "Build + Run" to try it.

You should be able to notice that `k.@cc.com` is considered as valid email address by angular's regex while it should not be. And my suggested regex correctly recognize that.

**Pull request merged**
