### PR TITLE
fix build/watch for people importing tasks into their own gulpfile

### PR DESCRIPTION
**Pull request by fholzer**
See Semantic-Org/Semantic-UI#2653

### CODE REVIEW

**Comment by fholzer** [comment]
This way, the gulp instance that is handed down to `rtl.js` supports gulp-help, as it adds new tasks to gulp.

**Comment by fholzer** [comment]
In case you're worried about idempotence of gulp-help, I tested it. You could do this
````javascript
var gulp = require('gulp-help')(require('gulp-help')(require('gulp-help')(require('gulp'))));

gulp.task('default', 'this is some default task', false, function(done) {
        console.log('some task output');
        done();
});
````
and still get the expected output
````
storm@linux-krxl:~/git/semanti-ui/patch/test> gulp 
[09:22:29] Using gulpfile ~/git/semanti-ui/patch/test/gulpfile.js
[09:22:29] Starting 'default'...
some task output
[09:22:29] Finished 'default' after 107 μs
storm@linux-krxl:~/git/semanti-ui/patch/test> gulp help
[09:26:40] Using gulpfile ~/git/semanti-ui/patch/test/gulpfile.js
[09:26:40] Starting 'help'...

Usage
  gulp [TASK] [OPTIONS...]

Available tasks
  default  this is some default task
  help     Display this help text.

[09:26:40] Finished 'help' after 978 μs
storm@linux-krxl:~/git/semanti-ui/patch/test>
````

**Comment by fholzer** [comment]
Sorry, didn't notice your comment on my other PR. Will close this now.

**Comment by jlukic** [comment]
How are you importing tasks, with two parameters or three? 

I think it might be a bit idiosyncratic to require other people who import the tasks to use `gulp-help`

**Comment by fholzer** [comment]
The alternative is to remove the gulp-help argument from gulp.task from all files that get sourced by `tasks/build.js` and `tasks/watch.js`. That would be nearly all tasks as can be seen when running `gulp help` in my [fixed version](https://github.com/fholzer/Semantic-UI-Issue-Showcase/tree/2653-fixed):
````
gulp help
[12:31:11] Using gulpfile ~\Documents\git\semantic-ui-tests\gulpfile.js
[12:31:11] Starting 'help'...

Usage
  gulp [TASK] [OPTIONS...]

Available tasks
  build
  build-assets                   Copies all assets from source
  build-css                      Builds all css from source
  build-javascript               Builds all javascript from source
  build-rtl                      Watch files as RTL
  default
  help                           Display this help text.
  package compressed css
  package compressed docs css
  package compressed docs js
  package compressed js
  package compressed rtl css
  package uncompressed css
  package uncompressed docs css
  package uncompressed docs js
  package uncompressed js
  package uncompressed rtl css
  watch
  watch-rtl                      Build all files as RTL

[12:31:11] Finished 'help' after 2.26 ms
````
As these come from files that are also sourced when running gulp from the semantic directory, removing the gulp-help argument from them would break running `gulp help` in the `semantic/` directory.
While keeping gulp-help around, *and* fixing the issue for users not directly using gulp-help in their `gulpfile.js` is just a matter of editing two files, and `gulp help` would still show all tasks when run from the `semantic/` directory.

The nice thing about my PR is that users aren't forced to use gulp-help in their gulp file, if they don't want to. Though even when they to, it will still work.

Negative side-effect: When users use gulp-help in their project, they also see all the semantic targets.
Though in order to prevent that, users shouldn't `require()` the semantic task files at the top of their `gulpfile.js`, but only in the task function that actually runs those tasks, [like so](https://github.com/fholzer/Semantic-UI-Issue-Showcase/commit/a8356f00ef3ee10f0c316a920ac19e61ab1f88ca). (Of course this also works file for people that don't use gulp-help.)

**Comment by jlukic** [comment]
I'll be evaluating this shortly.. hold tight

**Comment by jlukic** [comment]
I've tested this and it works as you say, using either gulp help or no gulp help in the imported `gulpfile.js` now works fine.

**Comment by jlukic** [comment]
I've created an example repository which I will include in docs to help people understand what to do.
https://github.com/Semantic-Org/Example-External-Gulpfile

**Pull request merged**
