### PR TITLE
Fix issue #4275

### PR DESCRIPTION
**Pull request by vinh123456789**
Fix issue #4275, when using useLabels: false, dropdown("clear") won't
remove class "active" from "item"

### CODE REVIEW

**Comment by davidkuhta** [comment]
If we're calling `module.remove.activeItem();` inside both the `if` and the `else`, shouldn't it be brought outside?
Something like:
```
clear: function() {
  if(module.is.multiple()) {
    module.remove.labels();
  }
  else {
    module.remove.selectedItem();
  }
  module.remove.activeItem();
  module.set.placeholderText();
  module.clearValue();
},
```

**Comment by vinh123456789** [comment]
You are right...
This is my first time contributions to a github's project, i'm so nervous that i will make a mistake, and here is it...

**Comment by davidkuhta** [comment]
Well technically it wasn't a mistake because your code worked, we just refactored. 😄 
And whatever way @jlukic goes with this PR, thanks for helping to make Semantic UI better.

**Comment by jlukic** [comment]
`remove labels` calls `remove values` so this would cause values to remove twice with labels.

Probably need
```javascript
clear: function() {
  if(module.is.multiple() && settings.useLabels) {
    module.remove.labels();
  }
  else {
    module.remove.selectedItem();
  }
  module.remove.activeItem();
  module.set.placeholderText();
  module.clearValue();
}
```

**Comment by jlukic** [comment]
Confirmed fix

**Comment by vinh123456789** [comment]
@jlukic is there any reason why `module.remove.activeItem()` can't be place outside of the `if else` statement?

**Comment by jlukic** [comment]
It is placed outside?

**Pull request closed without merging**
