### PR TITLE
Fix file permission

### PR DESCRIPTION
**Pull request by PeterDaveHello**
The dist files' have permission 755(-rwxr-xr-x) now,
but they are not executable,
so they should not have the execute permission,
change them to 644 (-rw-r--r--) will be better.

### CODE REVIEW

**Comment by jlukic** [comment]
Added in 7a0490c43e7c1b7105244820ac6296c66c4d97e6 updated in 347a791

Available in `next`

**Comment by PeterDaveHello** [comment]
May I ask why can't I see it been merged?

**Comment by PeterDaveHello** [comment]
I think you can at least cherry-pick them, so won't look like the changes been stolen :mask:

**Comment by PeterDaveHello** [comment]
Excuse me, should I send PR to `next` branch next time? Thanks.

**Comment by jlukic** [comment]
Yes, send `PR` to next. https://github.com/Semantic-Org/Semantic-UI#pull-requests

This is to allow for hotfixes on current released branch not being disrupted by development on next version.

**Comment by PeterDaveHello** [comment]
Sorry, that's my fault, I didn't notice that, will be careful next time, thanks for your explain :)

**Comment by jlukic** [comment]
Hopefully you will get contribute credit with GitHub. If not I'm sure there will be more chances.

**Comment by PeterDaveHello** [comment]
No problem, it's okay.

**Pull request closed without merging**
