### PR TITLE
Treatment for name[] identifier

### PR DESCRIPTION
**Pull request by mktm**
form.get.values: Treatment for name[] identifiers while getting the
values

With this you can use form('get values') and inputs with name attribute that is an array return the array of values set.

### CODE REVIEW

**Comment by mktm** [comment]
Sorry I don't know why the tabulation is always broken...
I have set on my project to 2 spaces no tabs, but still...

**Comment by jlukic** [comment]
I had to rework this a bit. This would work only when no [fields] array was passed into `get fields`

I also added similar lookup for `set fields`

**Comment by mktm** [comment]
Great! Although, I believe this still needs a bit of polishing.

For example, we can have fields with name like identifier[array][], identifier[array1][array2][]

Which I completely forgot about when I wrote this...

**Comment by jlukic** [comment]
This was more to solve the simplest case
http://semantic-ui.com/behaviors/form.html#writing-values

**Comment by mktm** [comment]
Well, it will return objects with "names[like][this]": []

With PHP at least it gets interpreted since it is sent as string to the server and it builds the correct array/object structure;

Easiest way to do this for a correct output in json format would be using eval in my pov.

I am not really in pursue of this perfect, this does what I needed server-side as I get the array as it should be.
Only client-side it is not proper format.

**Pull request merged**
