### PR TITLE
Codeblock

### PR DESCRIPTION
**Pull request by ns-phennessy**
Implements #1530 

This is a code block similar to what you might see on Github or Google Code.

I tried to stay consistent to the Semantic-UI standards. I wasn't sure what category this fit under, so I made it a `view`.
I pulled styles from other places in the framework and tried to use as many global variables as possible.

It is modular meaning that parts can be taken in and out as desired.

**Features**:
- Header container
  - For things like a file name, or actions that can be done on that code
  - Is attached to the top of the codeblock
- Code container
  - Where the actual code is hosted
  - It stands separate to the gutter, allowing for clean copying
  - Setup to hide scroll on overflow (JS could limit lines shown perhaps?)
- Code gutter
  - Shows line numbers or indicative icons (such as Github's codefolding)
- Footer container
  - Intended for meta information like file size or language
  - Has a divider element

**Issues / Considerations**:
- For the moment, I have not written any Javascript to do syntax highlighting or generate the line numbers for the gutter.
- The gutter and code block MUST have the same `monospace` font, otherwise the alignment of the two will not be correct

### CODE REVIEW

**Comment by mishak87** [comment]
Have you considered placement of comments between lines? Like is possible to do no github for example.

**Comment by ph7vc** [comment]
@mishak87: While it's certainly possible, that would be an enhancement for further down the road.

As of right now, this element lacks basic functionality like line number generation, syntax highlighting, etc.

**Comment by kvetoslavnovak** [comment]
ph7vc, this is really great, thank you. Nice to see other developer helping jlukic with Semantic UI. 
Looking forward your next contributions (my tip would be date picker/calendar module :-)

**Comment by ph7vc** [comment]
@kvetoslavnovak, feel free to contribute as well :smiley:

**Pull request closed without merging**
