### PR TITLE
Form Reset + Serialize

### PR DESCRIPTION
**Pull request by mktm**
Implementing a reset functionality to form module

I implemented this instead of using form native due to Semantic modules, such as checkbox and dropdown (select), plus to avoid having to do "return false" on submitting the form via Ajax.

As instance of module occurs, it will set a data value (defaultValue) to all field identifiers passed through.
As reset is called, it will look these fields and set their value to their respective defaults.
May need a bit more polishing, but works as expected.

Manual call: $('.ui.form').form('reset');

Working example: http://jsfiddle.net/mktm/y5zopezh/

### CODE REVIEW

**Comment by mktm** [comment]
I have added a serialize function for the module.

Example: http://jsfiddle.net/y5zopezh/1/

**Comment by jlukic** [comment]
Nice! I'll take a look at this for `1.8.0`

**Comment by mktm** [comment]
@jlukic I am just implementing another function and changing the location of some of the old ones:
 setDefaults to set.field.defaults

As well as a set.field.values function to set input/dropdown values by passing through an object with key:value
I had used this to do a CRUD via Ajax, and not having to go through each field on the form and set them one by one. Hopefully makes use for others.

I believe tonight I will be pushing this.

**Comment by jlukic** [comment]
Thanks for the update. I'll review tomorrow.

**Comment by jlukic** [comment]
Err today.. delayed

**Comment by jlukic** [comment]
All merged in and ready to go. Will add a version of your example to docs and give you credit in release notes.

**Comment by jlukic** [comment]
Rewriting `serialize` as `get value` and `get values`. More natural with write API, and less jargon.

**Comment by jlukic** [comment]
Modified to `get/read value(s)` so as not to disrupt `get.field` which is already using the name to grab field elements.

**Comment by jlukic** [comment]
Added ``clear` and dropdown `clear`

**Pull request merged**
