### PR TITLE
Break validation on first error

### PR DESCRIPTION
**Pull request by listepo**
@jlukic see https://jsfiddle.net/b21sgvkk/1/
rule ```emailExists``` running if rule ```email``` not valid and call many ajax requests on blur

### CODE REVIEW

**Comment by listepo** [comment]
@jlukic please review this PR

**Comment by listepo** [comment]
Ping

**Comment by jlukic** [comment]
It needs to run through all errors in order to create validation, you'll just need to check for conditions to abort XHR in your emailExists rule.

**Comment by listepo** [comment]
@jlukic thanks

**Pull request closed without merging**
