### PR TITLE
[Icons] Upgrade to Font Awesome 4.4

### PR DESCRIPTION
**Pull request by ImSanchez**
I'm new to GitHub. I would like to help so I went ahead and added the new icon classes from Font Awesome 4.4. I'm going to better organize them later if this is added.

### CODE REVIEW

**Comment by jlukic** [comment]
Hi, thanks for starting work on this. 

The files in dist/ are automatically generated, you'll need to modify 'themes/default/elements/icon.overrides'.

Generally each icon has a primary name. Aliases are at the end of the file. Make sure to keep the order in overrides which is by UTF content. This helps with updates

**Comment by ImSanchez** [comment]
Ah okay, thanks.

**Comment by kappaknight** [comment]
One recommendation: within the Currency section of this page - http://semantic-ui.com/elements/icon.html you can fill the last empty spot with the Bitcoin icon.

**Comment by kappaknight** [comment]
What about a credit card version of Bitcoin? (Similar to VISA, MC, Discover, Amex, etc.)

**Comment by jlukic** [comment]
Check other PR above.

**Pull request closed without merging**
