### PR TITLE
[Visibility] Fixed issue with infinite scrolling not triggering onBottomVisible

### PR DESCRIPTION
**Pull request by miketalley**
Visibility module was incorrectly using topPassed to determine if bottomVisible. It should use bottomPassed when making this determination.

Broken Fiddle Example: http://jsfiddle.net/miketalley/y1bu3Le0/
Working Fiddle Example: http://jsfiddle.net/miketalley/f6khxwqb/

### CODE REVIEW

**Comment by Banandrew** [comment]
Resolves #5289.

**Comment by daneren2005** [comment]
Can this get merged in the next minor release?  This basically breaks the entire component and it has been 4 months.  I have been waiting for the next minor release and was sad not to see this get merged in for 2.2.11.

**Comment by srissel** [comment]
I agree, please merge this into the next release.

**Comment by srissel** [comment]
Any news on this?
We'd greatly appreciate having this request merged into sUI.

**Comment by miketalley** [comment]
Updated fiddles and fixed merge conflict.

**Comment by jlukic** [comment]
Hi, this was fixed in https://github.com/Semantic-Org/Semantic-UI/commit/3bbaf137b575c660af12cc89d6b811a8ae15cb8c

The two JSfiddle from your first post are both working.

I notice the logic differs in our two fixes. I think the one in 3bbaf137b575c660af12cc89d6b811a8ae15cb8c is correct, as topVisible is specifically related to whether it is still on screen.

**Pull request closed without merging**
